# Generated by Django 5.2.11 on 2026-02-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('perfume', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('rating_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rating_count', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('top_note', models.JSONField(blank=True, default=list)),
                ('middle_note', models.JSONField(blank=True, default=list)),
                ('base_note', models.JSONField(blank=True, default=list)),
                ('perfumer1', models.CharField(blank=True, max_length=255)),
                ('perfumer2', models.CharField(blank=True, max_length=255)),
                ('mainaccord1', models.CharField(blank=True, max_length=100)),
                ('mainaccord2', models.CharField(blank=True, max_length=100)),
                ('mainaccord3', models.CharField(blank=True, max_length=100)),
                ('mainaccord4', models.CharField(blank=True, max_length=100)),
                ('mainaccord5', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'perfumes',
                'ordering': ['-rating_count'],
            },
        ),
    ]
