# Generated by Django 5.2.11 on 2026-03-01 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('perfume', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('rating_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rating_count', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('top_note', models.JSONField(blank=True, default=list)),
                ('middle_note', models.JSONField(blank=True, default=list)),
                ('base_note', models.JSONField(blank=True, default=list)),
                ('perfumer1', models.CharField(blank=True, max_length=255)),
                ('perfumer2', models.CharField(blank=True, max_length=255)),
                ('mainaccord1', models.CharField(blank=True, max_length=100)),
                ('mainaccord2', models.CharField(blank=True, max_length=100)),
                ('mainaccord3', models.CharField(blank=True, max_length=100)),
                ('mainaccord4', models.CharField(blank=True, max_length=100)),
                ('mainaccord5', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'perfumes',
                'ordering': ['-rating_count'],
            },
        ),
        migrations.CreateModel(
            name='PerfumeCollected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfume_type', models.CharField(choices=[('EDT', 'Eau de Toilette'), ('EDP', 'Eau de Parfum'), ('PARFUM', 'Parfum'), ('OTHER', 'Other')], default='EDT', max_length=100)),
                ('perfume_size', models.CharField(choices=[('SAMPLE', 'Sample'), ('DECANT', 'Decant'), ('MINI', 'Mini'), ('BOTTLE', 'Bottle')], default='SAMPLE', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfumes.perfume')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'db_table': 'perfume_collected',
                'unique_together': {('profile', 'perfume')},
            },
        ),
    ]
