# Generated by Django 5.2.11 on 2026-02-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_uid', models.UUIDField(unique=True)),
                ('username', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ManyToManyField(blank=True, related_name='collected_by', to='perfumes.perfume')),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
