# Generated by Django 5.2.11 on 2026-02-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
