# Generated by Django 5.2.11 on 2026-03-01 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("perfumes", "0003_review"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
