# Generated by Django 5.2.11 on 2026-03-01 16:53

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0006_auto_20260301_1150'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='perfume',
            index=django.contrib.postgres.indexes.GinIndex(fields=['brand'], name='brand_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='perfume',
            index=django.contrib.postgres.indexes.GinIndex(fields=['perfume'], name='perfume_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
