# Generated by Django 5.2.11 on 2026-03-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0007_perfume_brand_trgm_perfume_perfume_trgm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfumecollected',
            name='perfume_type',
        ),
        migrations.AlterField(
            model_name='perfumecollected',
            name='perfume_size',
            field=models.CharField(choices=[('SAMPLE', 'Sample'), ('DECANT', 'Decant'), ('MINI', 'Mini'), ('BOTTLE', 'Bottle')], default='BOTTLE', max_length=100),
        ),
    ]
