# Generated by Django 5.2.11 on 2026-03-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0008_remove_perfumecollected_perfume_type_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='perfumecollected',
            unique_together={('profile', 'perfume', 'perfume_size')},
        ),
    ]
