# Generated by Django 5.2.11 on 2026-03-01 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0009_alter_perfumecollected_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfume',
            options={},
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='rating_value',
        ),
    ]
