# Generated by Django 5.2.11 on 2026-03-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0010_alter_perfume_options_remove_perfume_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfume',
            options={'ordering': ['-rating_count']},
        ),
        migrations.AddField(
            model_name='perfume',
            name='rating_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='rating_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
