# Generated by Django 5.2.11 on 2026-03-08 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfumes", "0011_alter_perfume_options_perfume_rating_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyScent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=36)),
                ("day", models.DateField()),
                (
                    "perfume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perfumes.perfume",
                    ),
                ),
            ],
            options={
                "db_table": "daily_scent",
                "ordering": ["-day"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "day"), name="unique_user_day"
                    )
                ],
            },
        ),
    ]
