# Generated by Django 5.2.11 on 2026-03-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cologne_gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Slightly Female', 'Slightly Female'), ('Unisex', 'Unisex'), ('Slightly Male', 'Slightly Male'), ('Male', 'Male')], default='Unisex', max_length=20),
        ),
    ]
