# Generated by Django 5.2.11 on 2026-03-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfumes", "0012_add_daily_scent_fallback"),
        ("user", "0003_profile_cologne_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="wishlist",
            field=models.ManyToManyField(blank=True, to="perfumes.perfume"),
        ),
    ]
