# Generated by Django 5.2.11 on 2026-03-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0012_add_daily_scent_fallback'),
        ('user', '0004_review_unique_per_user_perfume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_fragrances',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='perfumes.perfume'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='perfumes.perfume'),
        ),
    ]
