# Generated by Django 5.2.11 on 2026-03-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='action',
            field=models.CharField(choices=[('COLLECTION_ADD', 'Collection Add'), ('COLLECTION_REMOVE', 'Collection Remove'), ('DAILY_SCENT_SET', 'Daily Scent Set'), ('DAILY_SCENT_REMOVE', 'Daily Scent Remove'), ('FOLLOW', 'Follow'), ('UNFOLLOW', 'Unfollow'), ('REVIEW_CREATE', 'Review Create'), ('REVIEW_UPDATE', 'Review Update'), ('REVIEW_DELETE', 'Review Delete'), ('WISHLIST_ADD', 'Wishlist Add'), ('WISHLIST_REMOVE', 'Wishlist Remove'), ('LIKE_FRAGRANCE', 'Like Fragrance'), ('UNLIKE_FRAGRANCE', 'Unlike Fragrance'), ('LIKE_REVIEW', 'Like Review'), ('UNLIKE_REVIEW', 'Unlike Review'), ('LIKE_COMMENT', 'Like Comment'), ('UNLIKE_COMMENT', 'Unlike Comment')], db_index=True, max_length=50),
        ),
    ]
