# Generated by Django 5.2.11 on 2026-03-01 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("perfumes", "0004_remove_review"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Female", "Female"),
                            ("Slightly Female", "Slightly Female"),
                            ("Unisex", "Unisex"),
                            ("Slightly Male", "Slightly Male"),
                            ("Male", "Male"),
                        ],
                        max_length=20,
                    ),
                ),
                ("winter", models.BooleanField(default=False)),
                ("spring", models.BooleanField(default=False)),
                ("summer", models.BooleanField(default=False)),
                ("autumn", models.BooleanField(default=False)),
                ("day", models.BooleanField(default=False)),
                ("night", models.BooleanField(default=False)),
                (
                    "longevity",
                    models.CharField(
                        choices=[
                            ("0 - 2 hours", "0 - 2 hours"),
                            ("2 - 4 hours", "2 - 4 hours"),
                            ("4 - 6 hours", "4 - 6 hours"),
                            ("6 - 8 hours", "6 - 8 hours"),
                            ("8-10 hours", "8-10 hours"),
                            ("10+ hours", "10+ hours"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("Super Overpriced", "Super Overpriced"),
                            ("Overpriced", "Overpriced"),
                            ("Alright", "Alright"),
                            ("Good Value", "Good Value"),
                            ("Super Value", "Super Value"),
                        ],
                        max_length=20,
                    ),
                ),
                ("maceration", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "perfume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="perfumes.perfume",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="user.profile",
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
