# Generated by Django 5.2.11 on 2026-03-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sillage',
            field=models.CharField(blank=True, choices=[('No Sillage', 'No Sillage'), ('Light Sillage', 'Light Sillage'), ('Moderate Sillage', 'Moderate Sillage'), ('Strong Sillage', 'Strong Sillage')], max_length=20, null=True),
        ),
    ]
