# Generated by Django 5.2.11 on 2026-03-10 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("perfumes", "0012_add_daily_scent_fallback"),
        ("reviews", "0002_review_sillage"),
        ("user", "0003_profile_cologne_gender"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("profile", "perfume")},
        ),
    ]
